config/routes.rb
Rails.application.routes.draw do
  namespace :emails do
    get "sent"
  end
  namespace :groups do
    get "delete_member"
  end
  resources :emails do 
    get "delete_from_show"
    get "add_to_favourites"
    get "remove_to_favourites"
  end
  resources :favourites ,only: [:index]
  devise_for :users,  :controllers => {:registrations => "users/registrations"}
  resources :users
  resources :groups


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "emails#index"
end

app/models/group.rb
class Group < ApplicationRecord
    has_and_belongs_to_many :users
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    before_action :set_group, only: %i[show edit update destroy delete_member]
    before_action :authenticate_user!
    def index 
        @groups = Group.where(user_email: current_user.email)
        respond_to do |format|
            format.html
            format.js
        end
    end

    def show 
    end

    def new
        @users = User.all
        @group = Group.new
    end

    def create
        
        @group = Group.new(group_params)
        @group.user_email = current_user.email
        if @group.save!
            params[:group][:users].each do |a|
                next if a ==""
                @group.users << User.find(a) 
            end
            redirect_to groups_path
        else
            render :new
        end
    end

    def edit
        @users = @group.users
    end

    def update
        if @group.update(group_params)
            redirect_to group_url(@group), notice: "Group was successfully updated."
        else
            render :edit, status: :unprocessable_entity
        end
    end 

    def delete_member
        @group = Group.find(params[:id])
        @group.users.delete(params[:delete_id])
        redirect_to groups_path
    end

    def destroy
        @group.destroy
            redirect_to group_url, notice: "Group was successfully destroyed."

    end
    
    private
    def set_group    
        @group = Group.find(params[:id])
    end

    def group_params
        params.require(:group).permit(:name,:user_email, :user =>[])
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>

  <%= f.select :users, @users.pluck(:name, :id), { include_blank: false },
                         { multiple: true, data: {controller: 'slim', slim_target: 'field'}} %>
  </div>
  <div class="actions mt-2 mb-2">
    <%= f.submit %>
  </div>
<% end %>
<% if !@group.new_record?%>
  <%@group.users.each do |a|%>
  <%= a.email%><%= link_to "remove",groups_delete_member_path(id: @group.id,delete_id: a.id)%><br>
  <%end%>
<%end%>

app/views/groups/edit.html.erb
<div class="row d-flex justify-content-start align-items-center mx-5"> 
    <div class=" col-xl-7"> 
<h1>Editing group</h1>
 <hr>
<%= render 'form' %>
 
<%= link_to 'Show', @group, class:"btn btn-secondary" %> 
<%= link_to 'Back', groups_path, class:"btn btn-secondary" %>
    </div>
</div>

app/views/groups/index.html.erb
<div class="row d-flex justify-content-start align-items-center mx-5"> 
  <div class=" col-xl-7"> 
        
<h1 >Listing groups</h1>
 <hr>
<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Users</th>
    <th></th>
    <th></th>
  </tr>
 
<% @groups.each do |group| %>
  <tr>
    <td><%= group.name %></td>
    <td><%= group.users.pluck(:email).join(",")%></td>
    <%#= link_to 'Show', group, class:"btn btn-outline-secondary" %>
    <td><%= link_to 'Edit', edit_group_path(group), class:"btn btn-outline-secondary" %></td>
    <td><%= button_to 'Destroy', group, method: :delete, class:"btn btn-outline-danger" %></td>
  </tr>
<% end %>
</table>
 
<br />
 
<%= link_to 'New group', new_group_path, class:"btn btn-secondary" %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="row d-flex justify-content-start align-items-center mx-5"> 
    <div class=" col-xl-7"> 
<h1>New group</h1>
 <hr>
<%= render 'form' %>
 
<%= link_to 'Back', groups_path %>
    </div>
</div>    

app/views/groups/show.html.erb
<div class="row d-flex justify-content-center align-items-center"> 
    <div class=" col-xl-7"> 
<p id="notice"><%= notice %></p>
 
<p>
  <b>Name:</b>
  <%= @group.name %>
</p>
<p>
  <b>users:</b>
  <%= @group.users.pluck(:email) %>
</p>
 
<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>
  </div>
</div>  