config/routes.rb
Rails.application.routes.draw do
  namespace :emails do
    get "sent"
  end
  namespace :groups do
    get "delete_member"
  end
  resources :emails do 
    get "delete_from_show"
    get "add_to_favourites"
    get "remove_to_favourites"
  end
  resources :favourites ,only: [:index]
  devise_for :users,  :controllers => {:registrations => "users/registrations"}
  resources :users
  resources :groups


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "emails#index"
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
    def index
        @email_ids= AllEmailFavourite.where(user_id: current_user.id).pluck(:email_id)
        @emails = Email.where(id: @email_ids)
    end
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/views/favourites/index.html.erb
<section class="vh-100 mx-2">
  <div class="container py-2 ">
    <div class="row d-flex justify-content-center align-items-center">
      <div class="col-12">
        <div class="card shadow-2-strong" style="border-radius: 1rem;">
          <div class="card-body  text-left">
          <table class="table table-striped">
            <tr>
              <th scope="col"> Sender </th>
              <th scope="col"> Title </th>
              <th scope="col"> Action </th>
            </tr>

            <% @emails.each do |email| %>
            <tr>
              <td><%= email.sender%></td>
              <td><%= email.title%></td>
              <td><%= link_to(image_tag("delete-icon.svg"), email_delete_from_show_path(email.id) )%></td>
            </tr>
            <% end %>
          </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>