config/routes.rb
Rails.application.routes.draw do
  namespace :emails do
    get "sent"
  end
  namespace :groups do
    get "delete_member"
  end
  resources :emails do 
    get "delete_from_show"
    get "add_to_favourites"
    get "remove_to_favourites"
  end
  resources :favourites ,only: [:index]
  devise_for :users,  :controllers => {:registrations => "users/registrations"}
  resources :users
  resources :groups


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "emails#index"
end

app/views/layouts/_navbar.html.erb
  <nav class="navbar navbar-expand-lg navbar-light fixed-top">
      <div class="container-fluid">
      <div class="d-flex align-items-center justify-content-center mx-2">
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="24" fill="currentColor" class="bi bi-box-fill" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M15.528 2.973a.75.75 0 0 1 .472.696v8.662a.75.75 0 0 1-.472.696l-7.25 2.9a.75.75 0 0 1-.557 0l-7.25-2.9A.75.75 0 0 1 0 12.331V3.669a.75.75 0 0 1 .471-.696L7.443.184l.004-.001.274-.11a.75.75 0 0 1 .558 0l.274.11.004.001 6.971 2.789Zm-1.374.527L8 5.962 1.846 3.5 1 3.839v.4l6.5 2.6v7.922l.5.2.5-.2V6.84l6.5-2.6v-.4l-.846-.339Z"/>
        </svg>
        <%= link_to "MyEmail", root_path, class: "navbar-brand "%>
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          </ul>
          <div class="d-flex">
            <% if user_signed_in?%>
              <%= form_tag(emails_path, method: 'get') do %>
              <%= text_field_tag(:search, params[:search]) %>
              <%= submit_tag("Search", name: nil,class:"btn btn-outline-warning") %>
            <% end %>
            <%#= link_to "Compose", new_email_path, class: "btn btn-outline-success mx-2"%>
              <%#= link_to "Groups", groups_path, class: "btn btn-outline-primary mx-2"%>
              <%= button_to "Sign out", destroy_user_session_path, class: "btn btn-danger mx-2", method: :delete, 'data-turbo': "false"%>
            <% else %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>

app/views/layouts/_side_panel.html.erb
<div class="d-flex flex-column flex-shrink-0 p-3 bg-light fixed-top fixed-bottom" style="width: 170px; min-height: calc(100vh - 62px); max-height: calc(100vh - 0px); background-color: #f0f3f6 !important; position: fixed; z-index: 9;">
  <h4 class="d-flex align-items-center designation mb-4"></h4>
  <label class="d-flex align-items-center full-name"><%#= "#{current_user.first_name.capitalize} #{current_user.last_name.capitalize}" %></label>
    <hr>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
  <ul class="nav nav-pills flex-column mb-auto ">
  <div class="d-flex align-items-center justify-content-center flex-column">
  <li>
    <%= link_to "Compose", new_email_path, class: "btn btn-outline-success mx-2"%>
  </li>
    <li>
    <button class="btn btn-sm mt-2">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-at" viewBox="0 0 16 16">
          <path d="M2 2a2 2 0 0 0-2 2v8.01A2 2 0 0 0 2 14h5.5a.5.5 0 0 0 0-1H2a1 1 0 0 1-.966-.741l5.64-3.471L8 9.583l7-4.2V8.5a.5.5 0 0 0 1 0V4a2 2 0 0 0-2-2H2Zm3.708 6.208L1 11.105V5.383l4.708 2.825ZM1 4.217V4a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v.217l-7 4.2-7-4.2Z"/>
          <path d="M14.247 14.269c1.01 0 1.587-.857 1.587-2.025v-.21C15.834 10.43 14.64 9 12.52 9h-.035C10.42 9 9 10.36 9 12.432v.214C9 14.82 10.438 16 12.358 16h.044c.594 0 1.018-.074 1.237-.175v-.73c-.245.11-.673.18-1.18.18h-.044c-1.334 0-2.571-.788-2.571-2.655v-.157c0-1.657 1.058-2.724 2.64-2.724h.04c1.535 0 2.484 1.05 2.484 2.326v.118c0 .975-.324 1.39-.639 1.39-.232 0-.41-.148-.41-.42v-2.19h-.906v.569h-.03c-.084-.298-.368-.63-.954-.63-.778 0-1.259.555-1.259 1.4v.528c0 .892.49 1.434 1.26 1.434.471 0 .896-.227 1.014-.643h.043c.118.42.617.648 1.12.648Zm-2.453-1.588v-.227c0-.546.227-.791.573-.791.297 0 .572.192.572.708v.367c0 .573-.253.744-.564.744-.354 0-.581-.215-.581-.8Z"/>
        </svg>
      <%= link_to "Inbox", emails_path, class: "nav-link link-dark"%>
    </button>
    </li>
    
    
    <li>
    <button class="btn btn-sm">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16">
            <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
        </svg>
      <%= link_to "Starred", favourites_path, class: "nav-link link-dark"%>
      </button>
    </li>

    <li>
    <button class="btn btn-sm">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-send" viewBox="0 0 16 16">
            <path d="M15.854.146a.5.5 0 0 1 .11.54l-5.819 14.547a.75.75 0 0 1-1.329.124l-3.178-4.995L.643 7.184a.75.75 0 0 1 .124-1.33L15.314.037a.5.5 0 0 1 .54.11ZM6.636 10.07l2.761 4.338L14.13 2.576 6.636 10.07Zm6.787-8.201L1.591 6.602l4.339 2.76 7.494-7.493Z"/>
        </svg>
      <%= link_to "Sent", emails_sent_path	, class: "nav-link link-dark"%>
    </button>
    </li>
    <li>
      <%= link_to "Groups", groups_path, class: "btn btn-outline-primary mx-2"%>
    </li>
    </div>
    </ul>
  <div class="nav-link">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
    </svg>
    <%= link_to "Edit Profile", edit_user_registration_path%>
  </div>
</div>                                                                                                      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyEmail</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link href="https://unpkg.com/slim-select@latest/dist/slimselect.css" rel="stylesheet"/>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
  <%#= render '/layouts/nav'%>
  <%#= render '/layouts/side_panel'%>
  <div class="row d-flex justify-content-center align-items-center"> 
    <div class=" col-xl-7"> 
  <p class="notice"><%#= notice %></p>
  <p class="alert"><%#= alert %></p>
  <%= render "/layouts/navbar"%>
    </div>
  </div>
          <% if user_signed_in? %>
        <div class="d-flex">
          <%= render "/layouts/side_panel"%>
          <div class="w-100" style="margin-left: 180px">
      <%#= button_to "Log out", destroy_user_session_path, method: :delete%>
            <%= yield%>
          </div>
        </div>
      <% else %>
        <%= yield%>
      <% end %>
  </body>
</html>